zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'

dynamodb:
        image: rajatvig/dynalite-alpine
        ports:
          - '8000:8000'

datastore:
        image: 'mastodonc/kixi.datastore:latest'
        #use volumes_from until we upgrade and get depends_on
        ports:
          - "8080:8080"
        volumes_from:
          - "dynamodb"
        volumes:
          - /tmp/kixi-datastore:/tmp/kixi-datastore
        links:
          - zookeeper:zookeeper
          - dynamodb:dynamodb
        environment:
          - CONFIG_PROFILE=local-kinesis
          - ZOOKEEPER=zookeeper
          - DYNAMODB=http://dynamodb:8000
          - COMMAND_STREAM=dev-witan-command
          - EVENT_STREAM=dev-witan-event
          - ENVIRONMENT=local-kinesis
        env_file:
          - aws-variables.env