dynamodb:
        image: rajatvig/dynalite-alpine
        ports:
          - '38000:8000'

datastore:
        image: 'mastodonc/kixi.datastore:latest'
        #use volumes_from until we upgrade and get depends_on
        ports:
          - "38001:38001"
        volumes_from:
          - "dynamodb"
        volumes:
          - ./tmp/kixi-datastore:/tmp/kixi-datastore
        links:
          - dynamodb:dynamodb
        environment:
          - CONFIG_PROFILE=local-kinesis
          - ZOOKEEPER=zookeeper
          - DYNAMODB=http://dynamodb:8000
          - COMMAND_STREAM=test-witan-httpapi-command
          - EVENT_STREAM=test-witan-httpapi-event
          - ENVIRONMENT=local-kinesis
          - VHOST=localhost
          - PORT=38001
        env_file:
          - aws-variables.env
